spring:
  data:
    redis:
      port: 26379
      password:
      sentinel:
        master: mymaster
        nodes:
          - highly-available-redis-example-redis-sentinel-1
          - highly-available-redis-example-redis-sentinel-2
          - highly-available-redis-example-redis-sentinel-3
      timeout: 600ms
